### ISSUE TITLE
Version release for Kubernetes 1.34 (25.0.0)

### ISSUE THREAD

**Issue by yue9944882** [kubernetes-client/java#4239]
Opening a tracking umbrella issue for tracking related tasks for publishing 25.0.0 release cc @brendandburns : 

- [x] Generate 1.34 API models
  - https://github.com/kubernetes-client/java/pull/4245
  - https://github.com/kubernetes-client/java/pull/4252
- [x] Bump root pom version to  25.0.0-SNAPSHOT
  - https://github.com/kubernetes-client/java/pull/4065
  - https://github.com/kubernetes-client/java/pull/4264
- [x] Run model generation job for 1.34 
  - Master branch: https://github.com/kubernetes-client/java/pull/4245
  - Legacy branch: https://github.com/kubernetes-client/java/pull/4252
- [ ] Cut release branch `release-25` and `release-legacy-25`
- [ ] Run release jobs for the above two branches
  - 25.0.0: https://github.com/kubernetes-client/java/pull/4342

**Comment by yue9944882** [comment]
The version release is currently blocked due to release credential issues..

**Comment by RyanDevlin** [comment]
Any update on this release? I work for an internal AWS team and we need this commit to allow us to use the AWS SDK v2 for our authentication: https://github.com/kubernetes-client/java/commit/b6f212982abf344a5048912e2e3f25899132d439

There has been no release since May so I'm curious when we are planning to release `v25.0.0`?

**Comment by eamansour** [comment]
We are also having problems with people upgrading to Kubernetes v1.34 and that version not being supported by the client-java library yet. What's the outlook for release v25.0.0 please?

**Comment by yue9944882** [comment]
@RyanDevlin we just fixed some release plugin and credential issue this week. the new release should be out by end of week

**Comment by yue9944882** [comment]
v25.0.0 is just out, should be available on maven central in ~1 day

**Comment by rjeberhard** [comment]
Will there also be a 25.0.0-legacy or have the issues with empty containers been resolved?

**Comment by rjeberhard** [comment]
@yue9944882, I've verified that v25.0.0 still doesn't have the fix for the default container issue, so can we please still have a 25.0.0-legacy release? I see that v25.0.0 is based on openapi-generator 7.13.0 and there is an apparent fix for the issue in 7.14.0. I'll update the other bug with the details as I'm willing to help fix it if I can get a little help with how the machinery works in this project.

**Comment by brendandburns** [comment]
@rjeberhard I saw that you recently updated the default version in the gen repo. I think that if I re-run the github action it should work, let me try that.

**Comment by rjeberhard** [comment]
Thanks, @brendandburns. I've been trying this too and I've not yet found a change to the Maven settings in java.xml that works. I'm starting to think that the maven plugin is not correctly passing the additional properties to the underlying generation run. I found this bug: https://github.com/OpenAPITools/openapi-generator/issues/21505.

**Comment by MaurizioCasciano** [comment]
Any update on this?
Maven version is still at 24.0.0
https://mvnrepository.com/artifact/io.kubernetes/client-java

**Comment by rjeberhard** [comment]
I've still not been successful at getting this to generate the expected Java bindings, so I'm going to switch gears and try again to work around the problem. Can you please initiate or when will version 25.0.0 show up on Maven Central?

**Comment by brendandburns** [comment]
@yue9944882 do we know when 25.0.0 will show up on maven central? I know we had some sonatype issues that (I think) got sorted out. Do we need to run the release again?

**Comment by yue9944882** [comment]
```
[INFO] Uploaded to ossrh: https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/io/kubernetes/client-java-extended/25.0.0/client-java-extended-25.0.0.pom (6.6 kB at 11 kB/s)
[INFO] Uploading to ossrh: https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/io/kubernetes/client-java-extended/25.0.0/client-java-extended-25.0.0.jar
...
```

strangely, the release job output says the artifact was successfully uploaded...

**Comment by yue9944882** [comment]
we're reaching out to maven central support team to debug this issue..

**Comment by yue9944882** [comment]
we just fixed the release workflow issue and published 25.0.0[-legacy] branch again. the artifact should be present on maven central in ~1 day.
